name: Capture LeetCode Profile Screenshot
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: sudo apt-get install -y libx11-xcb1 libxcb1 libxcb-dri3-0 libdrm2 libgbm1
        
      - name: Inspect Runner Environment
        run: |
          echo "Operating System: ${{ runner.os }}"
          echo "Node.js Version: ${{ env.RUNNER_TOOL_CACHE/node }}/bin/node"
          echo "Chrome Executable Path: $(which google-chrome)"       

      - name: Run Puppeteer
        run: node capture-screenshot.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "kiriti-desarkar"
          git config user.email "kiriti.desarkar.mails@gmail.com"
          git add .
          git commit -m "Update LeetCode profile screenshot"
          git push
